title: Contact Information
author: Eleni Schmitt
email: ems642@utulsa.edu

# social links
github_username:  schmitte7

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
